global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: show-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['show-service:8081']

  - job_name: booking-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['booking-service:8082']

  - job_name: booking-query-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['booking-query-service:8085']

  - job_name: payment-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['payment-service:8083']

  - job_name: notification-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['notification-service:8084']
