package com.workshop;

import au.com.dius.pact.provider.junit5.HttpTestTarget;
import au.com.dius.pact.provider.junit5.PactVerificationContext;
import au.com.dius.pact.provider.junitsupport.Provider;
import au.com.dius.pact.provider.junitsupport.State;
import au.com.dius.pact.provider.junitsupport.loader.PactFolder;
import au.com.dius.pact.provider.spring.junit5.PactVerificationSpringProvider;
import com.workshop.events.PaymentEvents;
import com.workshop.projection.PaymentProjection;
import com.workshop.projection.PaymentRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.TestTemplate;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.TestPropertySource;

import java.math.BigDecimal;

/**
 * Pact provider verification test for payment-service.
 * Reads Pact files generated by booking-service consumer tests from target/pacts.
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("dev")
@TestPropertySource(properties = {
        "spring.datasource.url=jdbc:h2:mem:pactdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE",
        "spring.flyway.enabled=false",
        "spring.jpa.hibernate.ddl-auto=create-drop",
        "axon.axonserver.enabled=false"
})
@Provider("payment-service")
@PactFolder("../booking-service/target/pacts")
class PaymentPactProviderTest {

    @LocalServerPort
    private int port;

    @Autowired
    private PaymentRepository paymentRepository;

    @BeforeEach
    void setUp(PactVerificationContext context) {
        context.setTarget(new HttpTestTarget("localhost", port));
    }

    @TestTemplate
    @ExtendWith(PactVerificationSpringProvider.class)
    void verifyPact(PactVerificationContext context) {
        context.verifyInteraction();
    }

    @State("payment service is available")
    void paymentServiceAvailable() {
        paymentRepository.deleteAll();
    }

    @State("payment payment-001 exists")
    void paymentExists() {
        paymentRepository.deleteAll();
        paymentRepository.save(PaymentProjection.builder()
                .paymentId("payment-001")
                .bookingId("booking-001")
                .customerId("customer-001")
                .amount(new BigDecimal("49.99"))
                .status("CONFIRMED")
                .build());
    }
}
